[package]
name = "balls"
version = "0.1.0"
authors = ["rayros <zniwus@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
[dependencies.stdweb]
version = "0.4.20"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]