[package]
name = "balls"
version = "0.1.0"
authors = ["rayros <zniwus@gmail.com>"]
edition = "2018"

[dependencies]
rand = {version = "0.7.3", features = ['stdweb']}
serde = { version = "1.0.104", features = ["derive"] }
[dependencies.stdweb]
version = "0.4.20"
